export  const rowsProduct = [//sản phẩm mới nhập
    {
      id: 1143155,
      product: "Acer Nitro 5",
      price:12,
      img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
      manufacturer: "John Smith",
      date: 2/2/2023,
      amount: 785,
      method: "Cash on Delivery",
      status: "Approved",
    },
    {
      id: 2235235,
      product: "Playstation 5",
      price:12,
      img: "https://m.media-amazon.com/images/I/31JaiPXYI8L._AC_UY327_FMwebp_QL65_.jpg",
      manufacturer: "Michael Doe",
      date: 2/2/2023,
      amount: 900,
      method: "Online Payment",
      status: "Pending",
    },
    {
      id: 2342353,
      product: "Redragon S101",
      price:12,
      img: "https://m.media-amazon.com/images/I/71kr3WAj1FL._AC_UY327_FMwebp_QL65_.jpg",
      manufacturer: "John Smith",
      date: 12/2023,
      amount: 35,
      method: "Cash on Delivery",
      status: "Pending",
    },
    {
      id: 2357741,
      product: "Razer Blade 15",
      price:12,
      
      img: "https://m.media-amazon.com/images/I/71wF7YDIQkL._AC_UY327_FMwebp_QL65_.jpg",
      manufacturer: "Jane Smith",
      date: 2/3/2023,
      amount: 920,
      method: "Online",
      status: "Approved",
    },
    {
      id: 2342355,
      product: "ASUS ROG Strix",
      price:12,

      img: "https://m.media-amazon.com/images/I/81hH5vK-MCL._AC_UY327_FMwebp_QL65_.jpg",
      manufacturer: "Harold Carol",
      date: 2/9/2023,
      amount: 2000,
      method: "Online",
      status: "Pending",
    },
  ];