export  const rowsProduct = [//sản phẩm mới nhập
    {
      id: 1143155,
      product: "Computer Destop PC",
      price:12,
      img: "https://i.ebayimg.com/images/g/qKQAAOSw~htnD7oE/s-l500.webp",
      manufacturer: "Ema",
      date: 2/2/2023,
      amount: 785,
      method: "Cash on Delivery",
      status: "Approved",
    },
    {
      id: 2235235,
      product: "Razer rz06 Black",
      price:12,
      img: "https://i.ebayimg.com/images/g/jAgAAOSwgwlmoehZ/s-l500.webp",
      manufacturer: "ELSA",
      date: 2/2/2023,
      amount: 900,
      method: "Online Payment",
      status: "Pending",
    },
    {
      id: 2342353,
      product: "Key Board Laptop",
      price:12,
      img: "https://i.ebayimg.com/images/g/5iUAAOSwthhiz49P/s-l500.webp",
      manufacturer: "Emma Ju",
      date: 12/2023,
      amount: 35,
      method: "Cash on Delivery",
      status: "Pending",
    },
    {
      id: 2357741,
      product: "CHUWI CoreBook",
      price:12,
      
      img: "https://i.ebayimg.com/images/g/mN0AAOSwDz9nLJ~i/s-l500.webp",
      manufacturer: "Jane Kim",
      date: 2/3/2023,
      amount: 920,
      method: "Online",
      status: "Approved",
    },
    {
      id: 2342355,
      product: "Mobile Phone GamePad",
      price:12,

      img: "https://i.ebayimg.com/images/g/dqMAAOSwWeNk~KfY/s-l500.webp",
      manufacturer: "Haru Sun",
      date: 2/9/2023,
      amount: 2000,
      method: "Online",
      status: "Pending",
    },
  ];
